import Vehicle from "../models/Vehicle";
import User from "../models/User";
import Driver from "../models/Driver";
import { logger } from "../lib/logger";
import bcrypt from "bcryptjs";

const DEMO_VEHICLES = [
  {
    name: "Toyota Innova Crysta",
    type: "van",
    capacity: 7,
    pricePerDay: 4500,
    pricePerKm: 14,
    location: "Delhi",
    features: ["AC", "GPS", "Music System", "USB Charging", "First Aid Kit"],
    imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop"],
    rating: 4.8,
    reviewCount: 312,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Mercedes-Benz E-Class",
    type: "luxury",
    capacity: 4,
    pricePerDay: 12000,
    pricePerKm: 28,
    location: "Mumbai",
    features: ["Leather Seats", "Climate Control", "Sunroof", "WiFi", "Chauffeur Ready"],
    imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop"],
    rating: 4.9,
    reviewCount: 187,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Maruti Swift Dzire",
    type: "car",
    capacity: 4,
    pricePerDay: 1800,
    pricePerKm: 10,
    location: "Bangalore",
    features: ["AC", "Power Steering", "Music System", "Central Locking"],
    imageUrl: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&auto=format&fit=crop"],
    rating: 4.5,
    reviewCount: 428,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Tempo Traveller 12-Seater",
    type: "van",
    capacity: 12,
    pricePerDay: 7500,
    pricePerKm: 18,
    location: "Jaipur",
    features: ["AC", "Push-back Seats", "Music System", "Large Luggage Space", "GPS"],
    imageUrl: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format&fit=crop"],
    rating: 4.6,
    reviewCount: 253,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "BMW 5 Series",
    type: "luxury",
    capacity: 4,
    pricePerDay: 15000,
    pricePerKm: 32,
    location: "Mumbai",
    features: ["Premium Leather", "Harman Kardon Audio", "Panoramic Sunroof", "ADAS", "WiFi Hotspot"],
    imageUrl: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=800&auto=format&fit=crop"],
    rating: 4.9,
    reviewCount: 94,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Mahindra XUV700",
    type: "car",
    capacity: 6,
    pricePerDay: 5500,
    pricePerKm: 15,
    location: "Hyderabad",
    features: ["ADAS Safety", "Panoramic Sunroof", "Level 2 ADAS", "Sony 3D Sound", "360° Camera"],
    imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop"],
    rating: 4.7,
    reviewCount: 196,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Volvo AC Bus (32-Seater)",
    type: "bus",
    capacity: 32,
    pricePerDay: 22000,
    pricePerKm: 45,
    location: "Delhi",
    features: ["AC", "Recliner Seats", "Charging Points", "Entertainment Screen", "Toilet"],
    imageUrl: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&auto=format&fit=crop"],
    rating: 4.6,
    reviewCount: 118,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Toyota Fortuner",
    type: "car",
    capacity: 7,
    pricePerDay: 8000,
    pricePerKm: 20,
    location: "Goa",
    features: ["4WD", "Leather Seats", "Sunroof", "Rear AC", "Push-button Start"],
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop"],
    rating: 4.8,
    reviewCount: 261,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Honda Amaze Sedan",
    type: "car",
    capacity: 4,
    pricePerDay: 2200,
    pricePerKm: 11,
    location: "Pune",
    features: ["AC", "Bluetooth Audio", "Rear Camera", "Central Locking", "USB Charging"],
    imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop"],
    rating: 4.4,
    reviewCount: 375,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Kia Carnival Limousine",
    type: "luxury",
    capacity: 8,
    pricePerDay: 10000,
    pricePerKm: 24,
    location: "Bangalore",
    features: ["Captain Seats", "VIP Interior", "Rear Entertainment", "Star Ceiling", "Privacy Glass"],
    imageUrl: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&auto=format&fit=crop"],
    rating: 4.9,
    reviewCount: 82,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Mini Bus (20-Seater)",
    type: "bus",
    capacity: 20,
    pricePerDay: 12000,
    pricePerKm: 30,
    location: "Chennai",
    features: ["AC", "Comfortable Seats", "Music System", "GPS", "Emergency Exit"],
    imageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop"],
    rating: 4.5,
    reviewCount: 149,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Maruti Ertiga MPV",
    type: "van",
    capacity: 7,
    pricePerDay: 3200,
    pricePerKm: 12,
    location: "Ahmedabad",
    features: ["AC", "3-Row Seating", "Smart Play Studio", "Hill Hold Assist", "USB Charging"],
    imageUrl: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop"],
    rating: 4.6,
    reviewCount: 289,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Hyundai Creta SUV",
    type: "car",
    capacity: 5,
    pricePerDay: 3800,
    pricePerKm: 13,
    location: "Kolkata",
    features: ["Sunroof", "Ventilated Seats", "Bose Audio", "360° Camera", "Level 1 ADAS"],
    imageUrl: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop"],
    rating: 4.7,
    reviewCount: 334,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Rolls-Royce Ghost",
    type: "luxury",
    capacity: 4,
    pricePerDay: 55000,
    pricePerKm: 80,
    location: "Mumbai",
    features: ["Starlight Headliner", "Bespoke Audio", "Massage Seats", "Champagne Cooler", "Full Chauffeur Service"],
    imageUrl: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop"],
    rating: 5.0,
    reviewCount: 28,
    isAvailable: true,
    isApproved: true,
  },
  {
    name: "Tata Winger Van",
    type: "van",
    capacity: 15,
    pricePerDay: 6500,
    pricePerKm: 16,
    location: "Jaipur",
    features: ["AC", "16-Seater Config", "Large Boot", "GPS Tracked", "First Aid Kit"],
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop"],
    rating: 4.4,
    reviewCount: 167,
    isAvailable: true,
    isApproved: true,
  },
];

const DEMO_DRIVERS = [
  { name: "Rajesh Kumar", email: "rajesh.driver@yatrawheels.demo", city: "Delhi", license: "DL-2023-001", rating: 4.9, trips: 312 },
  { name: "Suresh Verma", email: "suresh.driver@yatrawheels.demo", city: "Delhi", license: "DL-2022-045", rating: 4.8, trips: 287 },
  { name: "Amit Singh", email: "amit.driver@yatrawheels.demo", city: "Mumbai", license: "MH-2023-088", rating: 4.7, trips: 195 },
  { name: "Pradeep Nair", email: "pradeep.driver@yatrawheels.demo", city: "Mumbai", license: "MH-2021-211", rating: 4.9, trips: 421 },
  { name: "Vikram Yadav", email: "vikram.driver@yatrawheels.demo", city: "Jaipur", license: "RJ-2022-067", rating: 4.8, trips: 243 },
  { name: "Manoj Patel", email: "manoj.driver@yatrawheels.demo", city: "Ahmedabad", license: "GJ-2023-134", rating: 4.6, trips: 158 },
  { name: "Ravi Sharma", email: "ravi.driver@yatrawheels.demo", city: "Bangalore", license: "KA-2022-092", rating: 4.9, trips: 376 },
  { name: "Karthik Reddy", email: "karthik.driver@yatrawheels.demo", city: "Hyderabad", license: "TS-2023-055", rating: 4.7, trips: 201 },
  { name: "Deepak Mishra", email: "deepak.driver@yatrawheels.demo", city: "Goa", license: "GA-2022-029", rating: 4.8, trips: 168 },
  { name: "Sanjay Tiwari", email: "sanjay.driver@yatrawheels.demo", city: "Kolkata", license: "WB-2023-143", rating: 4.6, trips: 134 },
];

export async function seedDatabase(): Promise<void> {
  const vehicleCount = await Vehicle.countDocuments();
  if (vehicleCount === 0) {
    const inserted = await Vehicle.insertMany(DEMO_VEHICLES);
    logger.info({ count: inserted.length }, "Demo vehicles seeded successfully");
  } else {
    logger.info({ count: vehicleCount }, "Vehicles exist — skipping vehicle seed");
  }

  const hashedPw = await bcrypt.hash("Driver@123", 10);
  let seededCount = 0;
  for (const d of DEMO_DRIVERS) {
    const existingUser = await User.findOne({ email: d.email });
    if (existingUser) continue;
    const user = await User.create({
      name: d.name,
      email: d.email,
      password: hashedPw,
      role: "driver",
      phone: "",
    });
    await Driver.create({
      userId: user._id,
      licenseNumber: d.license,
      licenseUrl: "",
      city: d.city,
      isAvailable: true,
      status: "approved",
      rating: d.rating,
      reviewCount: Math.floor(d.trips * 0.6),
      totalTrips: d.trips,
      totalEarnings: d.trips * 1000,
    });
    seededCount++;
  }
  if (seededCount > 0) {
    logger.info({ count: seededCount }, "Demo drivers seeded successfully");
  } else {
    logger.info("All demo drivers already exist — skipping");
  }
}
